"""Constants for the gridX integration."""

from dataclasses import dataclass
from typing import Final

DOMAIN: Final = "gridx"

# Auth0 — shared across every gridX OEM
AUTH0_TOKEN_URL: Final = "https://gridx.eu.auth0.com/oauth/token"
AUTH0_AUDIENCE: Final = "my.gridx"
AUTH0_SCOPE: Final = "email openid offline_access"
AUTH0_GRANT_TYPE: Final = "http://auth0.com/oauth/grant-type/password-realm"

# gridX API
API_BASE_URL: Final = "https://api.gridx.de"
API_GATEWAYS_URL: Final = f"{API_BASE_URL}/gateways"
API_LIVE_URL: Final = f"{API_BASE_URL}/systems/{{}}/live"
API_HISTORICAL_URL: Final = f"{API_BASE_URL}/systems/{{}}/historical"

# Polling
DEFAULT_SCAN_INTERVAL: Final = 60
ERROR_SCAN_INTERVAL_BASE: Final = 120
ERROR_SCAN_INTERVAL_MAX: Final = 900

# Auth cooldown
AUTH_COOLDOWN_SECONDS: Final = 60

# Transient connection retries (DNS timeout, connection refused, etc.)
# Auth0 hostnames have CNAME chains (gridx.eu.auth0.com → pivot.prod.auth0edge.com
# → cdn.cloudflare.net) with 2s TTLs on intermediate hops, making DNS lookups
# more brittle than for single A-record hosts. Retry transient connection
# errors with exponential backoff before giving up to the coordinator.
# HTTP-level errors (4xx, 5xx) are NOT retried here.
CONNECTION_RETRIES: Final = 3
CONNECTION_RETRY_DELAY: Final = 1.0  # seconds, doubles each retry

# hass.data keys
COORDINATOR_LIVE: Final = "live_coordinator"
COORDINATOR_HISTORICAL: Final = "historical_coordinator"

# SG Ready states (from gridX OpenAPI spec)
SG_READY_STATES: Final = ["UNKNOWN", "OFF", "AUTO", "RECOMMEND_ON", "ON"]

# Config entry keys
CONF_PROVIDER: Final = "provider"


@dataclass(frozen=True)
class Provider:
    """A gridX-backed OEM portal.

    Every OEM uses the same Auth0 tenant, audience, scope, grant type and
    backend (api.gridx.de). Only client_id and realm differ.
    """

    key: str
    label: str
    client_id: str
    realm: str


DEFAULT_PROVIDER: Final = "eon_home"

# --- BEGIN PROVIDERS (auto-generated by scripts/update_providers.py) ---
# Extracted from the gridX multi-tenant SPA bundle served at
# https://homeone.gridx.de/. Re-run the script periodically to pick up new
# OEMs or rotated client IDs.
PROVIDERS: Final[dict[str, Provider]] = {
    "1komma5grad": Provider(
        key="1komma5grad",
        label="1KOMMA5°",
        client_id="CrqUiQt6VhwOgWHqkX40CgYNlhABF3dB",
        realm="1komma5grad-authentication-db",
    ),
    "efa_home": Provider(
        key="efa_home",
        label="EFA-Home",
        client_id="VsgghMKZYiSku5OUo6B5MenBf8XmTA8z",
        realm="efa-home-authentication-db",
    ),
    "empavo": Provider(
        key="empavo",
        label="empavo",
        client_id="SGi5e55lb4kPlx54sTwqmSx50agfGkkp",
        realm="empavo-authentication-db",
    ),
    "enviam": Provider(
        key="enviam",
        label="enviaM",
        client_id="ubZZBgnq9W9cNksekUuWWsw73bB3SVLv",
        realm="enviam-authentication-db",
    ),
    "eon_feh_nl": Provider(
        key="eon_feh_nl",
        label="E.ON FEH (NL)",
        client_id="VpunLkvfSk0CYnfFeZPeceEPb88ihoEZ",
        realm="eon-feh-nl-authentication-db",
    ),
    "eon_home": Provider(
        key="eon_home",
        label="E.ON Home Manager",
        client_id="mG0Phmo7DmnvAqO7p6B0WOYBODppY3cc",
        realm="eon-home-authentication-db",
    ),
    "evm": Provider(
        key="evm",
        label="EVM",
        client_id="63FyqwVC8z5s0Ej7fk4epfHhvr1rVJiD",
        realm="evm-authentication-db",
    ),
    "ewv": Provider(
        key="ewv",
        label="EWV",
        client_id="0IYvvxIwlP4OxPF9PLwjZCem5U1yibgn",
        realm="ewv-authentication-db",
    ),
    "giedorf": Provider(
        key="giedorf",
        label="Giedorf",
        client_id="cUC6Lo5Rly2Vkx0KqwmPnb5KXGk8FK5R",
        realm="giedorf-authentication-db",
    ),
    "greenblocks": Provider(
        key="greenblocks",
        label="Greenblocks",
        client_id="EsfZCmULf0yhads5dwMNMEd5WFgEzeei",
        realm="greenblocks-authentication-db",
    ),
    "heimwatt": Provider(
        key="heimwatt",
        label="Heimwatt",
        client_id="EWf6tTifj13GK8GwrlnRkrKsMnh4LFLb",
        realm="heimwatt-authentication-db",
    ),
    "hemos": Provider(
        key="hemos",
        label="hemos",
        client_id="q9OlJhQGhkf0OzW356VLw6UzlR3qgWhh",
        realm="hemos-authentication-db",
    ),
    "ibc_homeone": Provider(
        key="ibc_homeone",
        label="IBC HomeOne Hub",
        client_id="F9aEJdfve0nL65yA0aWSdCwiWqDYIHgm",
        realm="ibc-homeone-authentication-db",
    ),
    "klarsolar": Provider(
        key="klarsolar",
        label="KlarSolar",
        client_id="48CcbpQ77QfqdSKkxsmFBl1yQTLZM219",
        realm="klarsolar-authentication-db",
    ),
    "lew": Provider(
        key="lew",
        label="LEW (Lechwerke)",
        client_id="4FDgJwNbBxwWBzvQHXjQqOsum8R7cKVR",
        realm="lew-authentication-db",
    ),
    "octopus": Provider(
        key="octopus",
        label="Octopus Energy",
        client_id="tBL5sAPBmZI2X9pA7lXX6rAiP7NXdOnu",
        realm="octopus-authentication-db",
    ),
    "pvgreen": Provider(
        key="pvgreen",
        label="PV Green",
        client_id="dbWuzhZqII1x0yX3SzzfHxsKxhZ91qzO",
        realm="pvgreen-authentication-db",
    ),
    "swnor": Provider(
        key="swnor",
        label="Stadtwerke Norderstedt",
        client_id="Ssg8OSIHDjquuyRKxIjBj6YWCfDcCyHj",
        realm="swnor-authentication-db",
    ),
    "upvolt": Provider(
        key="upvolt",
        label="upVolt",
        client_id="rcGfmimyTQONxjY3BAfUNvHMjI2RL4QD",
        realm="upvolt-authentication-db",
    ),
    "viessmann": Provider(
        key="viessmann",
        label="Viessmann GridBox (legacy, realm shut down end of 2025)",
        client_id="oZpr934Ikn8OZOHTJEcrgXkjio0I0Q7b",
        realm="viessmann-authentication-db",
    ),
    "zero_1": Provider(
        key="zero_1",
        label="Zero 1",
        client_id="7fMy9SJcViJzKqfcwYcjcgwMlbgbC7SH",
        realm="zero-1-authentication-db",
    ),
}
# --- END PROVIDERS ---
