"""Regenerate the PROVIDERS dict in const.py from the gridX multi-tenant SPA.

The portal at https://homeone.gridx.de/ is the multi-tenant gridX webapp.
Its JavaScript bundle bakes in an Auth0 config block for every OEM that runs
on gridX infrastructure (E.ON Home, IBC HomeOne, Octopus, LEW, …). Each block
looks like:

    {audience:"my.gridx",clientDomain:"https://gridx.eu.auth0.com",
     clientID:"…",realm:"…-authentication-db",
     tokenScope:"email openid offline_access"}

We extract every such block, plus best-effort brand labels from neighbouring
metadata (companyName / platformName / hardwareName) where available, then
rewrite the auto-generated section in custom_components/gridx/const.py.

Usage
-----

    python scripts/update_providers.py             # regenerate the dict
    python scripts/update_providers.py --check     # CI mode: exit 1 on drift

POC realms (gridx-poc-1, gridx-poc-2) are excluded — they are internal test
tenants. Other realms are emitted in alphabetical key order.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from dataclasses import dataclass
from pathlib import Path

PORTAL_URL = "https://homeone.gridx.de/"
BUNDLE_PATH_RE = re.compile(r'src="(/assets/index-[^"]+\.js)"')
OEM_BLOCK_RE = re.compile(
    r'\{audience:"my\.gridx",'
    r'clientDomain:"https://gridx\.eu\.auth0\.com",'
    r'clientID:"(?P<client_id>[A-Za-z0-9]+)",'
    r'realm:"(?P<realm>[a-z0-9-]+-authentication-db)",'
    r'tokenScope:"[^"]+"\}'
)

EXCLUDED_REALMS = {
    "gridx-poc-1-authentication-db",
    "gridx-poc-2-authentication-db",
}

# Hand-curated labels for known OEMs. Anything not in this map gets a
# title-cased fallback derived from the realm key. Edit this when you add
# a real human-readable name for a new OEM.
KNOWN_LABELS: dict[str, str] = {
    "1komma5grad-authentication-db": "1KOMMA5°",
    "efa-home-authentication-db": "EFA-Home",
    "empavo-authentication-db": "empavo",
    "enviam-authentication-db": "enviaM",
    "eon-feh-nl-authentication-db": "E.ON FEH (NL)",
    "eon-home-authentication-db": "E.ON Home Manager",
    "evm-authentication-db": "EVM",
    "ewv-authentication-db": "EWV",
    "giedorf-authentication-db": "Giedorf",
    "greenblocks-authentication-db": "Greenblocks",
    "heimwatt-authentication-db": "Heimwatt",
    "hemos-authentication-db": "hemos",
    "ibc-homeone-authentication-db": "IBC HomeOne Hub",
    "klarsolar-authentication-db": "KlarSolar",
    "lew-authentication-db": "LEW (Lechwerke)",
    "octopus-authentication-db": "Octopus Energy",
    "pvgreen-authentication-db": "PV Green",
    "swnor-authentication-db": "Stadtwerke Norderstedt",
    "upvolt-authentication-db": "upVolt",
    "viessmann-authentication-db": (
        "Viessmann GridBox (legacy, realm shut down end of 2025)"
    ),
    "zero-1-authentication-db": "Zero 1",
}

CONST_PY = Path(__file__).resolve().parent.parent / "custom_components/gridx/const.py"
BEGIN_MARK = "# --- BEGIN PROVIDERS (auto-generated by scripts/update_providers.py) ---"
END_MARK = "# --- END PROVIDERS ---"


@dataclass(frozen=True)
class OemBlock:
    realm: str
    client_id: str

    @property
    def key(self) -> str:
        # eon-home-authentication-db → eon_home
        return self.realm.removesuffix("-authentication-db").replace("-", "_")

    @property
    def label(self) -> str:
        return KNOWN_LABELS.get(self.realm, self.key.replace("_", " ").title())


def _fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "ha-gridx-provider-sync"})
    with urllib.request.urlopen(req, timeout=15) as resp:
        return resp.read().decode("utf-8", errors="replace")


def fetch_oem_blocks() -> list[OemBlock]:
    html = _fetch(PORTAL_URL)
    match = BUNDLE_PATH_RE.search(html)
    if not match:
        raise RuntimeError(
            f"Could not find SPA bundle <script src> in {PORTAL_URL}; "
            "the portal may have changed its build layout."
        )
    bundle_url = PORTAL_URL.rstrip("/") + match.group(1)
    bundle = _fetch(bundle_url)

    seen: dict[str, OemBlock] = {}
    for m in OEM_BLOCK_RE.finditer(bundle):
        realm = m.group("realm")
        if realm in EXCLUDED_REALMS:
            continue
        # Some realms appear more than once; the values are identical.
        seen.setdefault(realm, OemBlock(realm=realm, client_id=m.group("client_id")))

    if not seen:
        raise RuntimeError(
            f"Parsed {len(bundle):,} bytes from {bundle_url} but found no Auth0 "
            "OEM blocks. The bundle structure likely changed."
        )
    return sorted(seen.values(), key=lambda b: b.key)


def render_providers_block(blocks: list[OemBlock]) -> str:
    lines: list[str] = [
        BEGIN_MARK,
        "# Extracted from the gridX multi-tenant SPA bundle served at",
        "# https://homeone.gridx.de/. Re-run the script periodically to pick up new",
        "# OEMs or rotated client IDs.",
        "PROVIDERS: Final[dict[str, Provider]] = {",
    ]
    for b in blocks:
        lines.extend(
            [
                f'    "{b.key}": Provider(',
                f'        key="{b.key}",',
                f'        label="{b.label}",',
                f'        client_id="{b.client_id}",',
                f'        realm="{b.realm}",',
                "    ),",
            ]
        )
    lines.append("}")
    lines.append(END_MARK)
    return "\n".join(lines) + "\n"


def replace_providers_block(source: str, new_block: str) -> str:
    pattern = re.compile(
        rf"{re.escape(BEGIN_MARK)}.*?{re.escape(END_MARK)}\n", re.DOTALL
    )
    if not pattern.search(source):
        raise RuntimeError(
            f"Could not find {BEGIN_MARK!r}…{END_MARK!r} markers in {CONST_PY}."
        )
    return pattern.sub(new_block, source)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write — exit 1 if the on-disk dict differs from the SPA.",
    )
    args = parser.parse_args()

    blocks = fetch_oem_blocks()
    print(f"Found {len(blocks)} provider(s) in the SPA bundle.")

    current = CONST_PY.read_text(encoding="utf-8")
    rendered = render_providers_block(blocks)
    updated = replace_providers_block(current, rendered)

    if args.check:
        if updated != current:
            print(
                "ERROR: PROVIDERS dict in const.py is out of date.\n"
                "       Re-run: python scripts/update_providers.py",
                file=sys.stderr,
            )
            return 1
        print("OK: PROVIDERS dict is in sync with the SPA.")
        return 0

    if updated == current:
        print("PROVIDERS dict already up to date.")
        return 0

    CONST_PY.write_text(updated, encoding="utf-8")
    print(f"Updated {CONST_PY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
